### ISSUE TITLE
server.go needs to add a sync.WaitGroup

### ISSUE THREAD

**Issue by purpleidea** [prashanthpai/sunrpc#1]
Need to do a wg.Wait() in Stop() with the appropriate wg.Add(1) and defer wg.Done() in the main loop.
If this makes sense, please add it, if not I can add the patch. But important to think about I think.

HTH

**Comment by purpleidea** [comment]
I guess I'll write this patch...

**Comment by purpleidea** [comment]
Sorry this is in https://github.com/gluster/glusterd2/blob/master/servers/sunrpc/server.go#L128

**Comment by prashanthpai** [comment]
Sunrpc is just the codec (encodes/decodes into/from sunrpc) library used by sunrpc server implementation.  As you pointed out, whatever you intend to fix should be done in glusterd2. I'm closing this issue.

If you do find an issue with the codec itself, feel free to file open another issue.
