### ISSUE TITLE
Opaque Datatype

### ISSUE THREAD

**Issue by dweidenfeld** [prashanthpai/sunrpc#2]
Hi,

thank you for the great library, but I still have some problems using it.

I am currently writing an NFS Server / Client implementation, but I am struggeling with the Opaque Datatype.
How should this type be handled by/with your library?
Could you give me an example?

Thanks :)

**Comment by prashanthpai** [comment]
Hi @dweidenfeld 
Do you mean opaque data type from [XDR](https://tools.ietf.org/html/rfc4506#section-4.9) ?

**Comment by dweidenfeld** [comment]
Yep exactly :)

**Comment by prashanthpai** [comment]
The sunrpc codec uses the [xdr](https://github.com/rasky/go-xdr/) library for encoding/decoding. So sunrpc codec doesn't handle that. I'll close this one now. I'll check out the other issue you posted.
