### ISSUE TITLE
unexpected EOF while decoding 260 bytes

### ISSUE THREAD

**Issue by dweidenfeld** [prashanthpai/sunrpc#3]
Hi,

as you might have seen my other issue there is another thing I need help:

I am constantly getting this error:
```
2018/03/14 07:25:29 xdr:DecodeFixedOpaque: unexpected EOF while decoding 260 bytes - read: '[0 0 0 0 0 0 0 1 0 0 0 10 107 101 114 110 101 108 46 111 114 103 0 0 0 0 0 70 76 105 110 117 120 32 52 46 49 53 46 56 45 49 45 65 82 67 72 32 35 49 32 83 77 80 32 80 82 69 69 77 80 84 32 83 97 116 32 77 97 114 32 49 48 32 48 48 58 48 48 58 51 51 32 85 84 67 32 50 48 49 56 32 120 56 54 95 54 52 0 0 0 0 0 0 0 0 0 0 0 0 0 0]'
```

I am trying to implement the Compound() function from the NFS protocol, but I am still at the very beginning and cannot implement the whole struct, so I just started with the one union case.

Here are my datatypes:

```go
type COMPOUND4args struct {
	Tag          string
	MinorVersion uint32
	ArgArray     []NFSArgOp4
}

type NFSArgOp4 struct {
	ArgOp        int32           `xdr:"union"`
	OpExchangeID EXCHANGEID4args `xdr:"unioncase=42"`
}

type EXCHANGEID4args struct {
	EiaClientOwner  ClientOwner4
	EiaFlags        uint32
	EiaStateProtect StateProtect4
	EiaClientImplID NfsImplID4
}

type ClientOwner4 struct {
	CoVerifier Verifier4
	CoOwnerId  Opaque
}

type Verifier4 Opaque

type Opaque struct {}

type StateProtect4 struct {
	SpaHow      int32            `xdr:"union"`
	SpaMachOps  StateProtectOps4 `xdr:"unioncase=1"`
	SpaSsvParms SsvSpParms4      `xdr:"unioncase=2"`
}

type StateProtectOps4 struct {
	SpoMustEnforce Bitmap4
	SpoMustAllow   Bitmap4
}

type Bitmap4 uint32

type SsvSpParms4 struct {
	SspOps           StateProtectOps4
	SspHashAlgs      SecOid4
	SspEncrAlgs      SecOid4
	SspWindow        uint32
	SspNumGssHandles uint32
}

type SecOid4 Opaque

type NfsImplID4 struct {
	NiiDomain string
	NiiName   string
	NiiDate   NfsTime4
}

type NfsTime4 struct {
	Seconds  int64
	NSeconds uint32
}
```

I hope nothing is missing :laughing: 

As you can see it is related to my other issue. I don't know how to get the Compound() call working with the unioncase=42 (ExchangeID) only.
You can read the specification at https://tools.ietf.org/html/rfc5661#page-392

Thank you for every kind of help :)

PS: Is there a way to debug the the EOF issue?

**Comment by dweidenfeld** [comment]
@prashanthpai I invited you to my repo on bitbucket, maybe you can figure out what I am doing wrong :)

**Comment by prashanthpai** [comment]
>PS: Is there a way to debug the the EOF issue?

You can take a look at the [code](https://github.com/rasky/go-xdr/blob/master/xdr/decode.go#L305-L335) which decodes the opaque structure. For isolating the problem, you can may be capture tcpdump+wireshark and inspect the bytes.

**Comment by dweidenfeld** [comment]
@prashanthpai 
I've nailed down the issue to the CoOwnerId (https://tools.ietf.org/html/rfc5661#page-23)
As described it is a variable length opaque data type. So I think it is wrong to call the fixed-length opaque decoding function. Instead it should call the variable-length opaque decoding.
See: https://docs.oracle.com/cd/E26502_01/html/E35597/xdrproto-31244.html#xdrproto-34

**Comment by prashanthpai** [comment]
I think this is incorrect:

```go
type Opaque struct {}
```

Opaque is rather a slice of bytes.

```go
type ClientOwner4 struct {
	CoVerifier Verifier4
	CoOwnerId  []byte
}
```

or

```go
type ClientOwner4 struct {
	CoVerifier Verifier4
	CoOwnerId  [NFS4_OPAQUE_LIMIT]byte
}
```

**Comment by dweidenfeld** [comment]
Well. I've completely removed the `Opaque` type and defined everything as `[]byte` or `[size]byte`.

```go
type ClientOwner4 struct {
	CoVerifier Verifier4
	CoOwnerID  []byte
}

type Verifier4 [NFS4VerifierSize]byte

type StateProtect4 struct {
	SpaHow      int32            `xdr:"union"`
	SpaMachOps  StateProtectOps4 `xdr:"unioncase=1"`
	SpaSsvParms SsvSpParms4      `xdr:"unioncase=2"`
}

type StateProtectOps4 struct {
	SpoMustEnforce Bitmap4
	SpoMustAllow   Bitmap4
}

type SsvSpParms4 struct {
	SspOps           StateProtectOps4
	SspHashAlgs      SecOid4
	SspEncrAlgs      SecOid4
	SspWindow        uint32
	SspNumGssHandles uint32
}

type Bitmap4 uint32

type SecOid4 []byte
```

But it still fails with:
```
2018/03/14 10:45:31 xdr:DecodeFixedOpaque: unexpected EOF while decoding 1801810544 bytes - read: '[101 108 46 111 114 103 0 0 0 0 0 70 76 105 110 117 120 32 52 46 49 53 46 56 45 49 45 65 82 67 72 32 35 49 32 83 77 80 32 80 82 69 69 77 80 84 32 83 97 116 32 77 97 114 32 49 48 32 48 48 58 48 48 58 51 51 32 85 84 67 32 50 48 49 56 32 120 56 54 95 54 52 0 0 0 0 0 0 0 0 0 0 0 0 0 0]'
```

If I change it to 
```go
const (
	NFS4OpaqueLimit  = 1024
)

type ClientOwner4 struct {
	CoVerifier Verifier4
	CoOwnerID  [NFS4OpaqueLimit]byte
}
```
(see: https://tools.ietf.org/html/rfc5661#section-3.1)

I am getting the following error
```
2018/03/14 10:48:20 xdr:DecodeFixedOpaque: unexpected EOF while decoding 1024 bytes - read: '[0 0 0 25 76 105 110 117 120 32 78 70 83 118 52 46 50 32 100 119 101 105 100 101 110 102 101 108 100 0 0 0 0 0 1 3 0 0 0 0 0 0 0 1 0 0 0 10 107 101 114 110 101 108 46 111 114 103 0 0 0 0 0 70 76 105 110 117 120 32 52 46 49 53 46 56 45 49 45 65 82 67 72 32 35 49 32 83 77 80 32 80 82 69 69 77 80 84 32 83 97 116 32 77 97 114 32 49 48 32 48 48 58 48 48 58 51 51 32 85 84 67 32 50 48 49 56 32 120 56 54 95 54 52 0 0 0 0 0 0 0 0 0 0 0 0 0 0]'
```

If I am right, the `CoOwnerID` is not a fixed length opaque but a variable length opaque and I think this is not supported by the library, is it?

**Comment by prashanthpai** [comment]
According to the [documentation](https://godoc.org/github.com/rasky/go-xdr/xdr2#hdr-Go_Type_to_XDR_Type_Mappings) the library does support it

```
[]byte <-> XDR Variable-Length Opaque Data
[#]byte <-> XDR Fixed-Length Opaque Data
```

**Comment by dweidenfeld** [comment]
Okay, well if I set it to a fixed length of 25 it works, but the given information are wrong (this is no problem with the library, I just have to figure out what should be mapped where).

But I think I got it, so I will open an issue on the xdr library side ;)

Thanks for the support
